spring.application.name=sportlased

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7gs46pkh4rs73adkj5g-a.virginia-postgres.render.com:5432/decathlon_database?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=decathlon_user
spring.datasource.password=KZqqVlW9vAPr8lFBMu6rl3ixbOw5B0IG